using System;
using System.Collections.Generic;

namespace AtlasIQMVP.WebAPI.DataAccess.Models
{
    public partial class ProspectPortalRealEstate
    {
        public int Id { get; set; }
        public string Databankid { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string Parcelid { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public double? Lat { get; set; }
        public double? Lon { get; set; }
        public string Streetview { get; set; }
        public byte? Featured { get; set; }
        public string Previoustenant { get; set; }
        public string Currentprevioususe { get; set; }
        public string Businesspark { get; set; }
        public string Buildingname { get; set; }
        public string Buildingtype { get; set; }
        public double? Buildingsize { get; set; }
        public double? Sitesize { get; set; }
        public double? Available { get; set; }
        public double? Contiguous { get; set; }
        public double? Divisiblefrom { get; set; }
        public double? Ceilingmin { get; set; }
        public double? Ceilingmax { get; set; }
        public byte? Forsale { get; set; }
        public byte? Forlease { get; set; }
        public string Leasetype { get; set; }
        public double? Leasecost { get; set; }
        public double? Saleprice { get; set; }
        public double? Pricepersf { get; set; }
        public int? Dockhigh { get; set; }
        public byte? Drivein { get; set; }
        public byte? Parking { get; set; }
        public string Parkingratio { get; set; }
        public byte? Divisible { get; set; }
        public string Zoning { get; set; }
        public byte? Sprinklered { get; set; }
        public string Loadbearing { get; set; }
        public byte? Multitenant { get; set; }
        public int? Yearbuilt { get; set; }
        public byte? Shovelready { get; set; }
        public string Subclassification { get; set; }
        public string Ownership { get; set; }
        public byte? Networked { get; set; }
        public int? Tradezone { get; set; }
        public string Phase1 { get; set; }
        public int? Airportzone { get; set; }
        public string Airportzonename { get; set; }
        public string Responsible { get; set; }
        public byte? Revitalizationarea { get; set; }
        public int? Tif { get; set; }
        public int? Enterprisezone { get; set; }
        public byte? Floodplain { get; set; }
        public byte? Poweronsite { get; set; }
        public string Electric { get; set; }
        public byte? Seweronsite { get; set; }
        public string Sewer { get; set; }
        public byte? Gasonsite { get; set; }
        public string Gas { get; set; }
        public byte? Wateronsite { get; set; }
        public string Water { get; set; }
        public byte? Telecomonsite { get; set; }
        public string Telecom { get; set; }
        public double? Distancehighway { get; set; }
        public string Highway { get; set; }
        public double? Distanceairport { get; set; }
        public string Airport { get; set; }
        public double? Distanceinterstate { get; set; }
        public string Interstate { get; set; }
        public byte? Israil { get; set; }
        public double? Distancerail { get; set; }
        public string Rail { get; set; }
        public double? Distanceport { get; set; }
        public string Port { get; set; }
        public string Brokerfirstname { get; set; }
        public string Brokerlastname { get; set; }
        public string Brokercompany { get; set; }
        public string Brokeraddress1 { get; set; }
        public string Brokeraddress2 { get; set; }
        public string Brokercity { get; set; }
        public string Brokerstate { get; set; }
        public string Brokerzip { get; set; }
        public string Brokerphone { get; set; }
        public string Brokerfax { get; set; }
        public string Brokeremail { get; set; }
        public string Brokerwebsite { get; set; }
        public string Edfirstname { get; set; }
        public string Edlastname { get; set; }
        public string Edcompany { get; set; }
        public string Edaddress1 { get; set; }
        public string Edaddress2 { get; set; }
        public string Edcity { get; set; }
        public string Edstate { get; set; }
        public string Edzip { get; set; }
        public string Edphone { get; set; }
        public string Edfax { get; set; }
        public string Edemail { get; set; }
        public string Edwebsite { get; set; }
        public string Edcellphone { get; set; }
        public DateTime? Created { get; set; }
        public int? Createdby { get; set; }
        public DateTime? Updated { get; set; }
        public int? Updatedby { get; set; }
        public string Landtype { get; set; }
        public string Imageimport { get; set; }
        public string Parentid { get; set; }
        public string Overrideimport { get; set; }
        public byte? Dataqualityscore { get; set; }
        public int? Truckdocks { get; set; }
        public string Secondrail { get; set; }
        public int? Gaspsi { get; set; }
        public int? Electricamps { get; set; }
        public double? Baywidth { get; set; }
        public double? Baylength { get; set; }
        public double? Gasmainsize { get; set; }
        public string Electricvolts { get; set; }
        public double? Sewermainsize { get; set; }
        public double? Watermainsize { get; set; }
        public string Fiber { get; set; }
        public string Salepriceunits { get; set; }
        public double? Floorthickness { get; set; }
        public int? Electricphase { get; set; }
        public string Rentalrateannual { get; set; }
        public int? Numbertruckdocks { get; set; }
        public string Pricenegotiable { get; set; }
        public int? Officeareasf { get; set; }
        public string Parkingpaved { get; set; }
        public string Rail2distance { get; set; }
        public string Addlacreageavail { get; set; }
        public DateTime? Expansiondate { get; set; }
        public string Dslavailable { get; set; }
        public string Constructionmaterial { get; set; }
        public string Cranesunderhook { get; set; }
        public string Expandabletosf { get; set; }
        public string Constructionmaterialsecondary { get; set; }
        public int? Dockslevel { get; set; }
        public bool? Expandableyesno { get; set; }
        public string Refrigeratedsf { get; set; }
        public string Heated { get; set; }
        public string Airconditioned { get; set; }
        public byte? Citylimits { get; set; }
        public int? Contactid { get; set; }
        public int? Photoindicator { get; set; }
        public string CreatedbyApc { get; set; }
        public int? ParkingApc { get; set; }
        public int? DistancerailApc { get; set; }
        public byte? Cranes { get; set; }
        public double? Maxcontig { get; set; }
        public string BuildableAcres { get; set; }
        public string CallCenter { get; set; }
        public string ColumnSpacing { get; set; }
        public string DataCenter { get; set; }
        public string HeatType { get; set; }
        public short? NumberDriveInDoors { get; set; }
        public byte? NumberOfStories { get; set; }
        public byte? NumberOfTruckDocks { get; set; }
        public bool? SepticOnSite { get; set; }
        public string SprinklerType { get; set; }
        public string Topography { get; set; }
        public int? WarehouseSf { get; set; }
        public string Wetlands { get; set; }
        public int? NumberOfParkingSpaces { get; set; }
        public bool? IsContiguous { get; set; }
        public DateTime? LastImportDate { get; set; }
        public string Brokercellphone { get; set; }
        public bool? Featuredsecondary { get; set; }
        public string FeaturedLabel { get; set; }
        public string Suite { get; set; }
        public byte? Providerid { get; set; }
        public int? Edcontactid { get; set; }
        public string ProximityToSubstation { get; set; }
        public string WasteWaterExcessCapacity { get; set; }
        public string WaterExcessCapacity { get; set; }
        public string RailDescription { get; set; }
        public string BuildingDimensions { get; set; }
        public string ContiguousAcresAvailableForDevelopment { get; set; }
        public string CapacityOfLargestBridgeCrane { get; set; }
        public string ReinforcedConcreteFloor { get; set; }
        public string Brownfield { get; set; }
        public byte? SoilBoringReportAvailable { get; set; }
        public string Kva { get; set; }
        public string FreightElevator { get; set; }
        public bool? IsOpportunityZone { get; set; }
    }
}
